version: '3'
services:
  db:
    image: postgres
    restart: always
    secrets:
      - db-password
      - db-name
      - db-user
    environment:
      - POSTGRES_DB_FILE=/run/secrets/db-name
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
      - POSTGRES_USER_FILE=/run/secrets/db-user
    volumes:
      - database:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080
    depends_on:
      - db

  fileservice:
    build: https://github.com/catinapoke/go-microservice.git
    image: go-microservice
    environment:
      - FILESERVICE_PATH=/var/fileservice/data
    ports:
      - 3001:3001
    volumes:
      - storage:/var/fileservice/data

  tgbot:
    build: .
    image: telegram-file-bot
    ports:
      - 2000:2000
    depends_on:
      - db
      - fileservice
    secrets:
      - tg-bot-token
      - db-password
      - db-name
      - db-user
    environment:
      - BOT_TOKEN_FILE=/run/secrets/tg-bot-token
      - DATABASE_URL=db:5432
      - FILESERVICE_URL=fileservice:3001
      - LISTEN_MODE=requests
      - POSTGRES_DB_FILE=/run/secrets/db-name
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
      - POSTGRES_USER_FILE=/run/secrets/db-user

secrets:
  db-password:
    file: ./tmp/db-password
  db-name:
    file: ./tmp/db-name
  db-user:
    file: ./tmp/db-user
  tg-bot-token:
    file: ./tmp/tg-bot-token

volumes:
  database:
    name: "database-volume"
  storage:
    name: "fileservice-storage"