version: '3'
services:
  db:
    image: postgres
    restart: always
    secrets:
      - db-password
      - db-name
      - db-user
    environment:
      - POSTGRES_DB_FILE=/run/secrets/db-name
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
      - POSTGRES_USER_FILE=/run/secrets/db-user
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080
    depends_on:
      - db

  fileservice:
    build: https://github.com/catinapoke/go-microservice.git
    image: go-microservice
    ports:
      - 3001:3001

  tgbot:
    build: .
    image: telegram-file-bot
    ports:
      - 2000:2000
    depends_on:
      - db
      - fileservice
    secrets:
      - tg-bot-token
      - db-password
      - db-name
      - db-user
    environment:
      - BOT_TOKEN_FILE=/run/secrets/tg-bot-token
      - DATABASE_URL=db
      - POSTGRES_DB_FILE=/run/secrets/db-name
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
      - POSTGRES_USER_FILE=/run/secrets/db-user

secrets:
  db-password:
    file: ./tmp/db-password
  db-name:
    file: ./tmp/db-name
  db-user:
    file: ./tmp/db-user
  tg-bot-token:
    file: ./tmp/tg-bot-token