version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080
    depends_on:
      - db

  fileservice:
    build: https://github.com/catinapoke/go-microservice.git
    image: go-microservice
    ports:
      - 3001:3001

  tgbot:
    build: github.com/catinapoke/telegram-file-bot.git
    image: telegram-file-bot
    depends_on:
      - db
      - fileservice